// Generated by CoffeeScript 1.6.3
var $, extendFunction, funs, handleExecute, self;

$ = {
  trim: function(data) {
    return data.trim();
  }
};

funs = [];

self = this;

extendFunction = function(body) {
  var f;
  f = new Function(body);
  f.prototype.mapResult = {};
  f.prototype.reduceResult = [];
  f.prototype.emit = function(key, value) {
    if (!this.mapResult[key]) {
      this.mapResult[key] = [];
    }
    return this.mapResult[key].push(value);
  };
  f.prototype.wrapMap = function(data) {
    var l, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = data.length; _i < _len; _i++) {
      l = data[_i];
      _results.push(this.map(l));
    }
    return _results;
  };
  f.prototype.wrapReduce = function() {
    var k, v, _ref, _results;
    _ref = this.mapResult;
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      _results.push(this.reduce(k, v));
    }
    return _results;
  };
  f.prototype.execute = function(data) {
    this.wrapMap(data);
    return this.wrapReduce();
  };
  return f;
};

handleExecute = function(data) {
  var a, f, tmp, _i, _j, _len, _len1, _ref;
  funs = [];
  _ref = data.funs;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    f = _ref[_i];
    funs.push(extendFunction(f));
  }
  tmp = data.data;
  for (_j = 0, _len1 = funs.length; _j < _len1; _j++) {
    f = funs[_j];
    a = (new f()).execute(tmp);
    tmp = a;
  }
  return postMessage(tmp);
};

this.addEventListener("message", function(e) {
  var data;
  data = e.data;
  switch (data.cmd) {
    case "execute":
      handleExecute(data);
  }
  return false;
});
